### ISSUE TITLE
Thoughts on the structure of the tutorial

### ISSUE THREAD

**Issue by jkanche** [BiocPy/tutorial#3]
- The Basics:
    - BiocFrames
    - Genomic analysis
    - delayed matrices (mattress package)
    - Representing experimental data (SE/SCE)
    - Multiple genomic experiments (MAE)
- Interop between R/Python (rds2py)
- Visualization
     - biocborn

**Comment by jkanche** [comment]
@LTLA what do you think?

**Comment by LTLA** [comment]
If this is a BiocPy tutorial, it seems like the "Analysis" section doesn't have much to do with it; you should be focusing on the data structures.
